version: "0.1" # for compatibility check, for now, error exit on any other value
guardians: # mapping of guardians
  lamianr-chain: # user defined name
    network-type: laminarChain # laminarChain | ethereum
    network: dev # dev | turbulence | reynolds | mainnet
    node-url: ws://localhost:9944 # Endpoint URL. Optional. If not specified, use our hosted node.
    monitors: # mapping of monitors to run
      # synthetic: # user defined name
      #   protocol: synthetic # synthetic | margin
      #   webhook: http://localhost:3000
      margin:
        task: margin.poolInfo
        arguments:
          poolId: 1
        actions:
          - method: script,
            path: ./src/__tests__/test.sh
  flow-ethereum: # another user defined name
    network-type: ethereum
    network: dev # dev | kovan | mainnet
    node-url: wss://kovan.infura.io/ws/v3/${INFRA_API_KEY} # Endpoint URL. Required except for dev, which default to http://localhost:8545
  #  monitors: # mapping of monitors to run
  #     synthetic: # user defined name
  #       protocol: synthetic # synthetic | margin
